import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Inter, Roboto, Poppins, Playfair_Display, Montserrat } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
});

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    preload: false,
});
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-roboto',
    preload: false,
});
const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '600'],
    variable: '--font-poppins',
    preload: false,
});
const playfairDisplay = Playfair_Display({
    subsets: ['latin'],
    variable: '--font-playfair-display',
    preload: false,
});
const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-montserrat',
    preload: false,
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto.variable} ${poppins.variable} ${playfairDisplay.variable} ${montserrat.variable}`}
                suppressHydrationWarning
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
